Feature/contest
AKABANEDAI-FES/2024-akabanedai-fes pull request #26
Opened 2024-10-18 07:47 UTC by mikoto2726

## ⭐️ 概要

- 変更点 1企画コンテストページを作成
- 変更点 2
- 変更点 3

## 😎 目的

写真を貼る以外完成したのでみて欲しい

## 📷 スクリーンショット

## 💬 関連する Issue

## 🖋️ 補足事項

2024-10-19 01:17 UTC, potepote1818 commented
クラスのところをclassName と書いていてテストが通ってないので直してください

2024-10-19 01:27 UTC, potepote1818 commented
スマホ表示するとデザインが崩れるのも直してほしいです

2024-10-19 07:22 UTC, yu7400ki requested changes
全体的に文字サイズ大きくない？
スマホ表示もちゃんと確認してね

2024-10-19 07:22 UTC, yu7400ki commented on src/app/globals.css
> +
フォントをどうするかは決まってなかった気がするので、今は設定しなくて大丈夫です
フォントファイルも消してしまってください

2024-10-19 07:22 UTC, yu7400ki commented on src/app/globals.css
> +		font-family: "Inter-VariableFont_opsz-wght", sans-serif;
同上

2024-10-19 07:22 UTC, yu7400ki commented on src/components/site/contest/about-contest/page.tsx
> +import "../contest.css";
CSS Modulesを使うこと

2024-10-19 07:22 UTC, yu7400ki commented on src/components/site/contest/award/page.tsx
> +"use client";
"use client`はクライアントサイドでJavaScriptを実行するときに必要なものなので、このファイルでは必要ないはず

2024-10-19 07:22 UTC, yu7400ki commented on src/components/site/contest/voting-period/page.tsx
> +"use client";
不要

2024-10-19 07:22 UTC, yu7400ki commented on src/components/site/contest/voting-period/page.tsx
> +				<span class="p-date2">11月3日 12:00~15:00</span>
`time`のほうが適切だと思われる
https://developer.mozilla.org/ja/docs/Web/HTML/Element/time

2024-10-19 07:22 UTC, yu7400ki commented on src/app/contest/page.tsx
> +			</nav>
パンくずリストは後々対応するので、今は消してしまって構わない

2024-10-19 07:22 UTC, yu7400ki commented on src/app/contest/page.tsx
> +			</button>
一旦無くて良い

ちなみにボタンの中にリンクを入れない
https://html.spec.whatwg.org/multipage/form-elements.html#the-button-element

2024-10-19 07:22 UTC, yu7400ki commented on src/app/contest/page.tsx
> +			</>
フラグメントは不必要

2024-10-19 07:22 UTC, yu7400ki commented on src/app/contest/contest.css
> +	color: #000000;
```suggestion
	color: var(--color-text);
```

2024-10-19 07:22 UTC, yu7400ki commented on src/app/contest/contest.css
> +	font-family: "BIZUDMincho-Regular", sans-serif;
```suggestion
	font-family: var(--font-serif);
```

2024-10-19 07:22 UTC, yu7400ki commented on src/app/contest/contest.css
> +}
```suggestion
strong {
	font-size: 36px;
}
```
後で対応します

2024-10-19 07:22 UTC, yu7400ki commented on src/components/site/contest/contest.css
> +	margin-left: 60px;
```suggestion
	font-size: 30px;
	margin-left: 60px;
```

2024-10-19 07:22 UTC, yu7400ki commented on src/components/site/contest/contest.css
> +	color: #000000;
```suggestion
	color: var(--color-text);
```

2024-10-19 07:22 UTC, yu7400ki commented on src/components/site/contest/contest.css
> +	margin-left: 60px;
```suggestion
	font-size: 30px;
	margin-left: 60px;
```

2024-10-19 07:22 UTC, yu7400ki commented on src/components/site/contest/how-to-vote/page.tsx
> +			</div>
画像がない間は要素自体無くて良い

2024-10-19 07:22 UTC, yu7400ki commented on src/app/contest/page.tsx
> +			<h1 style={{ color: "black" }}>企画コンテスト</h1>
```suggestion
			<h1>企画コンテスト</h1>
```
styleはなるべく使わない

2024-10-19 07:22 UTC, yu7400ki commented on src/components/site/contest/voting-period/page.tsx
> +				<span class="p-date2">11月3日 12:00~15:00</span>
`ul`とか使うと良いかもね

2024-10-19 07:22 UTC, yu7400ki commented on src/components/site/contest/voting-period/page.tsx
> +				<span class="p-date2">11月3日 12:00~15:00</span>
```suggestion
				<span className="p-date2">11月2日 12:00~18:00</span>
				<span className="p-date2">11月3日 12:00~15:00</span>
```

2024-10-19 07:42 UTC, mikoto2726 commented
figmaのサイズ見てデベロッパーツールでページ幅と高さそれにしてcssやってるんだけどどうやってる？

2024-10-19 08:26 UTC, potepote1818 commented
今回作ったfigmaは結構アバウトな感じなので大きさとかはなんとなくでやってます
サイズ感覚はほかのページ見ながらやってもらうといいと思います

2024-10-23 18:17 UTC, mikoto2726 commented
なとり君の指摘箇所直しました
スマホ対応表示とクソデカ文字は次修正します

2024-10-29 00:59 UTC, potepote1818 requested changes
もう少しフォントサイズを小さくしますか
h2は36pxくらい？
strongは24pxくらい？
他のフォントサイズはデフォルトの大きさでいい気がします

2024-10-29 05:12 UTC, potepote1818 requested changes
何度もすみません
h2のフォントサイズもう少し小さくしましょうか
32pxぐらい？

2024-10-30 15:30 UTC, potepote1818 approved these changes

2024-10-30 15:31 UTC, potepote1818 commented
LGTM

2024-10-30 15:38 UTC, yu7400ki approved these changes

2024-10-30 15:38 UTC, merged