Feature/guest guide page
AKABANEDAI-FES/2024-akabanedai-fes pull request #4
Opened 2024-10-09 08:39 UTC by potepote1818

## ⭐️ 概要

- Guideコンポーネントを作成
- AdmissionInfoのコンポーネントを作成
- Guidelinesのコンポーネントを作成
- HelpAndSuppoerのコンポーネントを作成
- guest-guideのページを作成

## 😎 目的
ご来場の皆様へのページの
入場について
キャンパス内での注意事項
困ったことがあったら
を完成
## 📷 スクリーンショット

![スクリーンショット 2024-10-09 173454](https://github.com/user-attachments/assets/7fc90241-bd62-4176-8ba4-93b7c6937af2)

## 💬 関連する Issue

## 🖋️ 補足事項

<!--
相談したい内容や残っている課題など、
伝えたい内容があれば記述してください。
また、関連するリンクや参考資料などがあれば教えて困ったことがあったら

2024-10-13 17:15 UTC, yu7400ki requested changes

2024-10-13 17:15 UTC, yu7400ki commented on .vscode/extensions.json
> +	}
これは`.vscode/settings.json`に書くやつ

2024-10-13 17:15 UTC, yu7400ki commented on src/app/guest-guide/guest-guide.module.css
> +	color: rgba(var(--color-blue), 0.7);
コントラストが低いから、もう少し色を濃くして

2024-10-13 17:15 UTC, yu7400ki commented on src/app/guest-guide/page.tsx
> +				</Link>
```suggestion
				<a href="#admissionInfo" className={styles.link}>
					入退場について
				</a>
```
タグへのリンクであれば`a`で大丈夫

2024-10-13 17:15 UTC, yu7400ki commented on src/app/guest-guide/page.tsx
> +				</Link>
```suggestion
				<a href="#guidelines" className={styles.link}>
					キャンパス内での注意事項
				</a>
```
同上

2024-10-13 17:15 UTC, yu7400ki commented on src/app/guest-guide/page.tsx
> +				</Link>
```suggestion
				<a href="#helpAndSupport" className={styles.link}>
					困ったことがあったら
				</a>
```
同上

2024-10-13 17:15 UTC, yu7400ki commented on src/app/guest-guide/page.tsx
> +			<div id="addmissionInfo" className={styles.linkScroll}>
```suggestion
			<div id="admissionInfo" className={styles.linkScroll}>
```
`addmission` -> `admission`

2024-10-13 17:15 UTC, yu7400ki commented on src/app/guest-guide/page.tsx
> +import styles from "./guest-guide.module.css";
```suggestion
import { HelpAndSupport } from "@/components/site/help-and-support";
import styles from "./guest-guide.module.css";
```
下の変更で不要なはず

2024-10-13 17:15 UTC, yu7400ki commented on src/components/site/guidelines/guidelines.tsx
> +			注意事項
メディアクエリで改行を調整するのは推奨しない
代わりに`inline-flex`を用いる

```suggestion
			<span>キャンパス内での</span>
			<span>注意事項</span>
```

2024-10-13 17:15 UTC, yu7400ki commented on src/components/site/guide/guide.module.css
> +.listItem {
改行の調整用
```suggestion
}

.heading span {
	display: inline-block;
}

.listItem {
```

2024-10-13 17:15 UTC, yu7400ki commented on src/components/site/admissionInfo/admission-info.tsx
> +	const headingText: React.ReactNode = <>入場について</>;
文字列で構わない
```suggestion
	const headingText = "入場について";
```

2024-10-13 17:15 UTC, yu7400ki commented on src/app/guest-guide/page.tsx
> +			<Heading>ご来場の皆様へ</Heading>
`Heading`はそこまで共通化できるように作ってないから、普通に`h1`使ってくれると助かる

2024-10-13 17:15 UTC, yu7400ki commented on src/components/site/help-and-support/help-and-support.tsx
> +		const headingText: React.ReactNode = <>困ったことがあったら</>;
```suggestion
		const headingText = "困ったことがあったら";
```

2024-10-13 17:17 UTC, yu7400ki commented on src/app/guest-guide/guest-guide.module.css
> +	color: rgba(var(--color-blue), 0.7);
`0.85`くらいなら大丈夫かな

2024-10-14 04:34 UTC, potepote1818 commented on .vscode/extensions.json
> +	}
直しました

2024-10-14 04:34 UTC, potepote1818 commented on src/app/guest-guide/guest-guide.module.css
> +	color: rgba(var(--color-blue), 0.7);
直しました

2024-10-14 04:34 UTC, potepote1818 commented on src/app/guest-guide/page.tsx
> +				</Link>
直しました

2024-10-14 04:34 UTC, potepote1818 commented on src/app/guest-guide/page.tsx
> +				</Link>
直しました

2024-10-14 04:35 UTC, potepote1818 commented on src/app/guest-guide/page.tsx
> +				</Link>
直しました

2024-10-14 04:35 UTC, potepote1818 commented on src/components/site/guidelines/guidelines.tsx
> +			注意事項
直しました

2024-10-14 04:35 UTC, potepote1818 commented on src/components/site/guide/guide.module.css
> +.listItem {
直しました

2024-10-14 04:36 UTC, potepote1818 commented on src/components/site/help-and-support/help-and-support.tsx
> +		const headingText: React.ReactNode = <>困ったことがあったら</>;
直しました

2024-10-14 04:46 UTC, yu7400ki approved these changes
LGTM

2024-10-14 04:47 UTC, merged